FROM python:3.11-slim

WORKDIR /app
RUN mkdir data

COPY main.py /app
COPY requirements.txt /tmp/

RUN pip install --no-cache-dir -r /tmp/requirements.txt

# Set environment variables
ENV POSTGRES_HOST=localhost
ENV POSTGRES_PORT=5433
ENV POSTGRES_DB=urbanfarm
ENV POSTGRES_USER=admin
ENV POSTGRES_PASSWORD=urbanfarm123

EXPOSE 8501

CMD ["streamlit", "run", "main.py", "--server.port", "8501"]