FROM python:3.11-slim

WORKDIR /app
RUN mkdir data

COPY main.py /app
COPY requirement.txt /tmp/
COPY data/spotify_top_songs_audio_features.csv data

RUN pip install --no-cache-dir -r /tmp/requirement.txt

EXPOSE 8501

CMD ["streamlit", "run", "main.py", "--server.port", "8501"]