apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: collecte-donnees
  name: collecte-donnees
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: collecte-donnees
  template:
    metadata:
      labels:
        io.kompose.network/urban-farm-default: "true"
        io.kompose.service: collecte-donnees
    spec:
      containers:
        - env:
            - name: API_HOST
              value: 0.0.0.0
            - name: API_PATH
              value: /receive
            - name: API_PORT
              value: "8080"
            - name: DB_HOST
              value: database
            - name: DB_NAME
              value: urbanfarm
            - name: DB_PASSWORD
              value: urbanfarm123
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: admin
          image: todin13/api-data-collection:0.1.0
          name: collecte-donnees
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
      restartPolicy: Always
