apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: sensor1
  name: sensor1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: sensor1
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose.yaml
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/urban-farm-default: "true"
        io.kompose.service: sensor1
    spec:
      containers:
        - env:
            - name: SCENARIO_ID
              value: "1"
            - name: SERVER_URL
              value: http://localhost:8080/receive
          image: abelfodil/sensor:0.0.1
          name: sensor1
      restartPolicy: Always
