apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: web-interface
  name: web_interface
spec:
  ports:
    - name: "8501"
      port: 8501
      targetPort: 8501
  selector:
    io.kompose.service: web-interface
